### ISSUE TITLE
Add new HeatingSystemType/FloorFurnace/extension/Any enumeration

### ISSUE THREAD

**Issue by GamalielL** [hpxmlwg/hpxml#101]
This type of system is common in some areas and currently causes problems with HES generation. OptiMIser designates floor furnaces using the HeatingSystemType/Other/Description enumeration.  This designation fails in the HPXML-HES translator.  If we had an a FloorFurnace enumeration, then the HPXML-HES translator could map it to the Wall Furnace option in the HES inputs.  Glenn Dickey has approved the use of WallFurnace as a workaround.  I'm currently instructing users to make that designation in the interface.  I could remap our HPXML translation, so that Floor Furnaces are specified as Wall Furnace in the xml, but I think it would be much better to have a Floor Furnace designation in HPXML.

**Comment by nmerket** [comment]
Sounds reasonable.
