### ISSUE TITLE
Add new third party building ID element

### ISSUE THREAD

**Issue by GamalielL** [hpxmlwg/hpxml#107]
HES recently introduced an external_building_id inputs which is being required by some programs.  The HPXML-HES translator currently maps the Building/BuildingID/SendingSystemIdentifierValue element to this input.  This is somewhat at odds with the standard use case.  For HES purposes that ID must be the same for all submissions.  In our standard use case, use this element to distinguish between pre and post retrofit building descriptions in a single HPXML file and they must have unique ID's.  

I think it would be much better if there were a new element created to store third party building ID's.  This could be useful for other integration with other applications, like Portfolio Manager, NEAT, etc.   I propose something like this:
Building/ThirdPartyBuildingID/ID string
Building/ThirdPartyBuildingID/Party string
Building/ThirdPartyBuildingID/SubmitToHES boolean
There could be multiple instances and the HES translator would take the fist with SubmitToHES=TRUE

**Comment by nmerket** [comment]
@GamalielL is the workaround in the HES translator good enough here?

**Comment by GamalielL** [comment]
It working fine for us.  Did you put it in the documentation?

I still think these could be a good addition, but they certainly aren't high priority.  I don't have a problem with closing this, if that's your preference.

**Comment by nmerket** [comment]
Yes, it is in the [documentation](http://hescore-hpxml.readthedocs.io/en/latest/translation/about.html#external-building-id). I'm going to close this then.
