### ISSUE TITLE
HPXML Inconsistencies

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#111]
List of various inconsistencies observed:

- [x] HeatingSystem/AnnualHeatingEfficiency vs HeatPump/AnnualHeatEfficiency
- [x] CoolingSystem/AnnualCoolingEfficiency vs HeatPump/AnnualCoolEfficiency
- [x] Measure/ReplacedComponents/ReplacedComponent vs Measure/InstalledComponent
- [x] Enclosure/Foundations/Foundation/FoundationWall/BelowGradeDepth vs Enclosure/Foundations/Foundation/Slab/DepthBelowGrade
- [x] WeatherStation/SystemIdentifiersInfo vs */SystemInfo
- [x] Enclosure/Walls/Wall vs Foundation/FoundationWall (also FrameFloor and Slab)
- [x] "central air conditioning" vs "room air conditioner" for CoolingSystemType (I suggest "central air conditioner")

**Comment by ecroteauwsf** [comment]
Additional inconsistency:
HeatingSystem/FractionHeatLoadServed is after HeatingSystem/AnnualHeatingEfficiency, suggest having this before HeatingSystem/AnnualHeatingEfficiency to be consistent with Cooling and HeatPump

**Comment by shorowit** [comment]
- [ ] For windows/skylights, the AttachedToFoo element is near the bottom, while for doors, the AttachedToFoo element is near the top.

**Comment by lirainer** [comment]
`Window/Treatments` and `Window/ExteriorShading` are mostly duplicate (e.g. `shade screen` in one, `shade screens` in the other). Suggest dropping `Treatments`.

**Comment by nmerket** [comment]
Moved window change into the window change issue #12. Closing this one as the other items have been addressed or we decided not to address them.
