### ISSUE TITLE
Add support for new UEF water heater efficiency specification

### ISSUE THREAD

**Issue by GamalielL** [hpxmlwg/hpxml#115]
I propose that we just add a new element
HPXML/Building/BuildingDetails/Systems/WaterHeating/WaterHeatingSystem/UnifiedEnergyFactor

**Comment by nmerket** [comment]
What is the definition of Unified Energy Factor?

**Comment by GamalielL** [comment]
*https://www.energystar.gov/products/water_heaters/residential_water_heaters_key_product_criteria
<https://www.energystar.gov/products/water_heaters/residential_water_heaters_key_product_criteria>*
*"Uniform Energy Factor (UEF):* The newest measure of water heater overall
efficiency. The higher the UEF value is, the more efficient the water
heater. UEF is determined by the Department of Energy’s test method
outlined in 10 CFR Part 430, Subpart B, Appendix E."

All manufactures must start using the UEF test method and put it on their
label by 12/27/2017.
