### ISSUE TITLE
Voluntary Window Venting

### ISSUE THREAD

**Issue by GamalielL** [hpxmlwg/hpxml#116]
OptiMiser and other modeling software tools have an option to model voluntary window venting as a cooling strategy to reduce loads on HVAC.  There is currently no way to specify this in HPXML and there are programs in CA that would like to track this setting in their QA process. 

I propose the addition of a boolean element:
HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl/VoluntaryWindowVenting

I'd put it here because it is essentially a user override of the HVAC control.

**Comment by nmerket** [comment]
So, this has been a while, I know. 

So, this basically means that the occupant opens the windows occasionally? It feels kind of ambiguous to me.

**Comment by pfairey** [comment]
Afraid I do not understand this message.

Philip Fairey
Sent from my iPhone
(o) 321-638-1005
(c) 321-537-6233

**Comment by GamalielL** [comment]
Yes, this means that the occupants open windows at night to pre-cool the house and keep them open on cooler days to vent internal and solar gains that would otherwise make the house too hot.  This effectively removes cooling load during shoulder seasons.  There was a problem in southern CA that was requiring auditors to use this feature and wanted to be able to track it.  I think they have dropped that requirement now.

**Comment by nmerket** [comment]
If they're not requiring it, let's table this then.
