### ISSUE TITLE
Create sub-components for storm windows, moveable insulation, shading devices

### ISSUE THREAD

**Issue by nmerket** [hpxmlwg/hpxml#12]
This idea came from #6. These three items are all elements attached to `Window` and `Skylight`. If a measure is performed such as adding moveable insulation, the entire window assembly has to be "replaced" in the measure, which is incorrect. If storm windows, moveable insulation, and shading devices were each their own sub-component under `Window` with a `SystemIdentifier`, then the measures could just show adding those items, which would make more sense. This is all kinds of breaking changes, though, so it'll have to go on the "someday" list.

**Comment by nmerket** [comment]
This should also handle [this redundancy](https://github.com/hpxmlwg/hpxml/issues/111#issuecomment-443914372) in windows.

**Comment by nmerket** [comment]
Add sub-elements to `Window` for 
- window film
    - shading/attenuation coefficient 
- exterior shading device (merge with window film?)
    - shading/attenuation coefficient 
- storm window
    - low-e
    - interior/exterior
    - frame type
    - glass type
    - operable?
    - condition
- moveable insulation
    - R-value
    - Insulation material

**Comment by nmerket** [comment]
@lirainer, see above. This might have big implications for the Home Energy Score workflow.

**Comment by lirainer** [comment]
These changes look good to me and adapting HEScore should be straightforward. One note:

Window films are always applied to the inside of glazing. Not sure why they currently show up in `Window/ExteriorShading`, but I think they should be added to `Window/InteriorShading`

**Comment by nmerket** [comment]
@shorowit could you look at what we're proposing here. How would this affect the HPXML workflows? I'm a little worried about making this change this late and how it'll affect us.

**Comment by shorowit** [comment]
Aside from the HPXML file we get from HEScore (that @lirainer spoke to above), I don't think our HPXML workflows are affected. 

[Here](https://github.com/NREL/OpenStudio-HPXML/blob/42052225be26287a7570b89298e399fc2a2b42d3/resources/EPvalidator.rb#L190-L201) are the elements that we use. I assume the `Overhangs`, `InteriorShadingFactorSummer`, and `InteriorShadingFactorWinter` elements remain unchanged?
