### ISSUE TITLE
Exterior insulation

### ISSUE THREAD

**Issue by DebraLittle** [hpxmlwg/hpxml#125]
Should we think about creating a way we can describe exterior insulation via location?  

So we can describe interior/cavity AND exterior. Now, I believe it doesn't accept both. 

CA has required continuous exterior insulation on new homes since Jan 2016. Also for some remodels. 
 Many other jurisdictions also require it.

**Comment by GamalielL** [comment]
It's already possible to have both cavity and continuous insulation layers
on a single surface, but we can't specify one as interior and the other as
exterior.

We have a InsulationLocation element, but unfortunately it's not located in
the Insulation/Layer level. Moving it to the Layer level, where we also
have InstallationType (cavity vs continuous) would solve this.
ᐧ
