### ISSUE TITLE
Fill out stud dimensions enumerated list

### ISSUE THREAD

**Issue by nmerket** [hpxmlwg/hpxml#132]
From #119: We should change the [Studs](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Walls/Wall/Studs) element so instead of specifying a size from an enumerated list as we do now:

```xml
<Studs>
    <Size>2x4</Size><!-- picked from enumerated list -->
</Studs>
```

Change it so we have a `StudWidth` and `StudDepth` element. These would be the nominal sizes and documented as such.

```xml
<Studs>
    <StudWidth>2</StudWidth>
    <StudDepth>4</StudDepth>
</Studs>
```

This is used in [Attic/Rafters](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/AtticAndRoof/Attics/Attic/Rafters/Size), [FrameFloor/FloorJoists](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Foundations/Foundation/FrameFloor/FloorJoists/Size), [FrameFloor/FloorTrusses](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Foundations/Foundation/FrameFloor/FloorTrusses/Size), [FoundationWall/InteriorStuds](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Foundations/Foundation/FoundationWall/InteriorStuds/Size), [RimJoist/FloorJoists](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/FloorJoists/Size), and [Wall/Studs](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Walls/Wall/Studs/Size)

**Comment by nmerket** [comment]
Let's just look at the enumerations and add any that are missing.

**Comment by shorowit** [comment]
It looks like we already added the missing 2x3 element: https://github.com/hpxmlwg/hpxml/pull/133
