### ISSUE TITLE
Add "wifi" to HVACControl/ControlType Enumeration List

### ISSUE THREAD

**Issue by MarcRoizman** [hpxmlwg/hpxml#139]
None of the [current enumerations](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Systems/HVAC/HVACControl/ControlType) really seem to describe smart/wifi thermostats.

**Comment by lirainer** [comment]
I suggest *connected*.

**Comment by juliecaracino** [comment]
#169
