### ISSUE TITLE
Standardize location enumerations

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#143]
Location enumerations for different elements are sometimes not consistent. Would be nice to create a single list of standardized locations that are referenced everywhere. Though we would probably need to still handle some unique enumerations for certain elements (like "mechanical closet" below, which is an acceptable water heater location, but probably not appropriate for wall exterior adjacent to).

Here's an example of differences:

**WaterHeatingSystem/Location**
    roof deck
    other exterior
    other interior
    mechanical closet
    garage - unconditioned
    garage - conditioned
    crawlspace - unvented
    crawlspace - vented
    conditioned space
    basement - unconditioned
    basement - conditioned
    attic - unconditioned
    attic - conditioned

**Wall/ExteriorAdjacentTo**
    other
    other housing unit
    unconditioned basement
    living space
    ground
    crawlspace
    attic
    garage
    ambient

cc @OneGeek

**Comment by shorowit** [comment]
Here's my attempt to summarize all the Location fields I could find in HPXML:
[Google Doc](https://docs.google.com/spreadsheets/d/1QfhMyKCwXChbKfOoux3TxoXZBPJWAOjQ55fUrDPazkQ/edit?usp=sharing)

**Comment by GamalielL** [comment]
I appreciate the improvement that this makes.  I've certainly been annoyed
by inconsistencies like this.  However, changes like this will add up to be
very costly for early adopters of HPXML who have fully developed
infrastructure.

**Comment by nmerket** [comment]
@GamalielL I feel your pain here, but we really should clean things like this up at some point. I'm hopeful there are some things we can do to ease the transition for established systems such as

- Make some thorough transition documentation and mapping.
- Possibly have a publicly available 2.x to 3.0 version translation tool. 
- Have a longer period of time between release of v3 and the general compliance expectation. 

What would make a transition like this easier for you guys?

**Comment by GamalielL** [comment]
A translation tool doesn't seem viable to me. It wouldn't help with new
elements that became program requirements and it would have to be supported
long term to be useful. It also sounds expensive to develop.

Good documentation would definitely be helpful.  A long transition period,
with significant lag time between when implementers are prepared to accept
v3 and when any new v3 features become program requirements would also be
helpful.

I don't have any other ideas at the moment. Ultimately the primary issue is
revenue/funding to make the HPXML support sustainable.

**Comment by shorowit** [comment]
I have added my initial proposal to the [Google Doc](https://docs.google.com/spreadsheets/d/1QfhMyKCwXChbKfOoux3TxoXZBPJWAOjQ55fUrDPazkQ/edit#gid=0). The spreadsheet shows both the current and proposed implementations, with changes highlighted in red.

**Comment by Tedkidd** [comment]
We would love "Unintentionally conditioned" as we have attics, basements, garages inside the shell that aren't necessarily directly heated, but they end up providing tremendous load reduction due to the fact they are adjacent to the conditioned space and thus reducing loss from the conditioned space. 

We found, particularly with redefined attics, modeled savings was not matching up to actual. Models show more energy use, actuals are showing less energy use. 

We suspect these unintentionally conditioned spaces are basically providing huge insulative benefits rather than additional load.
