### ISSUE TITLE
HVAC Static Pressures

### ISSUE THREAD

**Issue by ChrisCBaker** [hpxmlwg/hpxml#146]
A few years ago I recommended adding Supply and Return static pressure data within the  HVAC distribution system. Hoping we could revisit that idea.

Measured in Inches of Water Column (IWC) -industry standard.
Sample numbers would be
     0.250
    -0.250  (the negative sign implies it is the return side of the system.

**Comment by Tedkidd** [comment]
This is an incredibly important metric for us. 
Yes please.... Thumbs up twice if I could.

**Comment by ChrisCBaker** [comment]
Ditto! Statics are major for us too!

**Comment by nmerket** [comment]
@ChrisCBaker @Tedkidd Let's talk through the design of what this should be on the call Tuesday.

**Comment by Tedkidd** [comment]
k.

All blower motors sold are now ECM, so there are going to be a lot of
blower motors burning up on tight duct systems.

Sincerely,

*Ted Kidd*
*(585) 455-2658 Direct*
*Energy Smart Home Performance - steps to becoming a client
<http://bit.ly/ESHPsteps>*

*Recommended viewing*
Please read the fundamental chapter - Home Comfort 101
<http://bit.ly/HomePerformance101>

Buy the hardcopy - The Home Comfort Book
<https://www.amazon.com/gp/product/1979596883/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1979596883&linkCode=as2&tag=tedkidd-20&linkId=055b95a587c424b2da9c4d9338b87a15>
Step on our scale - Is your home fit or fat? <http://bit.ly/ESHPeuiCalc>
Play with Tesla Config - http://bit.ly/TeslaConfig
*Price externalities IN <http://bit.ly/CCLCarbonFeeAndDividend>, compensate
citizens for harm to commons <http://bit.ly/div4households>*

**Comment by nmerket** [comment]
This is already in 2.3 at https://hpxml.nrel.gov/datadictionary/2.3.0/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/TotalExternalStaticPressureMeasurement
