### ISSUE TITLE
Home Automation Features

### ISSUE THREAD

**Issue by juliecaracino** [hpxmlwg/hpxml#169]
Include data elements to support the ENERGY STAR SHEMS specification (forthcoming Sept 2019).

Question: Some of the 'dumb' versions of these technologies are in HPXML (under Building)
[Smart Technologies.xlsx](https://github.com/hpxmlwg/hpxml/files/3234020/Smart.Technologies.xlsx)

. Do we add an element to indicate that they're 'smart" or do we add a separate category for Smart Home Technologies or HEMS? See attached excel sheet for list of elements with definitions from EPA.

**Comment by juliecaracino** [comment]
At device level, may want to indicate whether it is IOT (connected) or within a home energy management system

**Comment by nmerket** [comment]
To discuss with @juliecaracino @TedKidd

**Comment by nmerket** [comment]
Notes from discussion

- Create a `Connected` (or something like that) sub-element that can be attached to
    - appliances
    - lighting
    - water heating
    - thermostats
    - room air conditioners
- Add an element for a home energy sub metering system. This should probably be a separate pull request. 
- Add smart plugs to as a type of [PlugLoadControl](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/MiscLoads/PlugLoadControl). Add `Connected` sub element to it.
- Add Smart Hub element. The `Connected` element could reference this as a device that controls it.
- What to do with occupancy sensors? They could be a property of devices (i.e. a thermostat "has a" occupancy sensor). Alternatively, they could be a separate device/element (i.e. a lighting group references an occupancy sensor that controls it.) As a separate element with a system identifier, they can be used and referenced in measures such as replacing a dumb light switch with an occupancy sensing light switch. Maybe we do both?
- We don't have a great way to talk about thermostats right now. The closest thing we have is [HVACControl](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Systems/HVAC/HVACControl), which does more to describe the logical control of the hvac systems than to describe a physical device that controls the hvac systems. We could co-opt that to include more device level stuff (manufacturer, serial number, Connected, etc) or we could make a separate thermostat element that implements an HVACControl. Open to suggestions here.
