### ISSUE TITLE
Add DHW controllers

### ISSUE THREAD

**Issue by GamalielL** [hpxmlwg/hpxml#172]
DHW timers are becoming a significant factor programs where TOU and demand rates are in use. I wasn't able to find any element that could communicate the presence of these devices.  I propose that we add a DHWController node.  I would put it in the WaterHeating node, at the same level as, but separate from the WaterHeatingSystem node.  It's important for it to be specified separately with it's own SystemIdentifier, so that it can be referenced independently in measures. I haven't learned enough yet about the range of available devices to specify a full list of elements.  Hopefully someone else on the forum has that knowledge.

**Comment by nmerket** [comment]
Sounds good to me. I don't know much about these either. Is someone willing to take some time and figure out a list of elements needed here?

**Comment by lirainer** [comment]
@GamalielL You are referring to DHW controllers that anticipate load and energy prices and adjust the set point accordingly? To be consistent with `HVAC/HVACControl` I suggest it be  called `WaterHeating/WaterHeatingControl`. I would be willing to work on a set of elements that should be included. There also is a need for a `HotWaterDistribution/HotWaterDistributionControl` node (for demand and circulation control systems), but that should probably be a separate issue.

**Comment by GamalielL** [comment]
@lirainer Yes, that's correct.  Also mechanical timers that just turn the system on and off on a schedule.

We already have recirculation controls under HotWaterDistribution/SystemType.

**Comment by nmerket** [comment]
@lirainer Thanks for volunteering to put forth a list of data elements for DHW controllers. Feel free to just throw a first cut as a bulleted list in this issue.

**Comment by nmerket** [comment]
At its most basic:

- Model
- Manufacturer
- Serial
- Control type
    - smart
       - communicating
       - learning
    - timer
    - temperature - fixed
    - temperature - variable

**Comment by nmerket** [comment]
We should add the `ConnectedDevice` from #198 here as well when that's available.

**Comment by nmerket** [comment]
- Indicate whether the `WaterHeatingSystem` has a mixing valve. 
- Put it _next to_ `WaterHeatingSystem`.
