### ISSUE TITLE
Fresh Air Strategy

### ISSUE THREAD

**Issue by Tedkidd** [hpxmlwg/hpxml#177]
We have moved to a pressurization fresh air strategy that includes humidity control recommendation and data logging. 

Is there a place for this in HPXML?

**Comment by nmerket** [comment]
I think this can be covered with the [MechanicalVentilation/FanType="supply"](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan/FanType).
