### ISSUE TITLE
Move FoundationWall (and Slab) elements inside Insulation/Layer

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#211]
If a `FoundationWall` has two continuous insulation layers (e.g., interior and exterior), there is currently no way to specify the `DistanceToTopOfInsulation` and `DistanceToBottomOfInsulation` properties for each of the layers.

To solve this, we should:
- `FoundationWall`: Move `DistanceToTopOfInsulation` and `DistanceToBottomOfInsulation` inside the `Insulation/Layer` element
- `Slab`: Move `PerimeterInsulationDepth` inside the `PerimeterInsulation/Layer` element
- `Slab`: Move `UnderSlabInsulationWidth` and `UnderSlabInsulationSpansEntireSlab` inside the `UnderSlabInsulation/Layer` element

This will take a little refactoring in order to have these elements only available in the `FoundationWall` (or `Slab`) `Insulation/Layer` elements and not _all_ surfaces.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-07-12](https://youtu.be/AWL1gD9Dh9M?t=2916)
