### ISSUE TITLE
Inconsistency in XML

### ISSUE THREAD

**Issue by tleslie-noresco** [hpxmlwg/hpxml#213]
Under HeatingSystemType, the type is entered as an xml element instead of value.

             <HeatingSystemType>
                <Furnace/>
              </HeatingSystemType>
while in CoolingSystemType it is entered correct as a value
              <CoolingSystemType>central air conditioner</CoolingSystemType>

If this is intentional, then it is fine it just make a parse of the file odd given that syntax

**Comment by nmerket** [comment]
Yes, this is (somewhat) intentional. The heating system type has additional information with each type which is why it is a `<xs:choice>` instead of an enumeration like cooling system type.
