### ISSUE TITLE
Standardize Quantity vs NumberofUnits vs Count

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#236]
Some elements use [Quantity](https://hpxml.nrel.gov/search/?query=quantity&version=67&expanded=False) while many others use [NumberofUnits](https://hpxml.nrel.gov/search/?query=Numberofunits&version=67&expanded=False) and a few use [Count](https://hpxml.nrel.gov/search/?query=count&version=67&expanded=False).

It'd be nice to use the same name everywhere. I like Quantity myself. I dislike NumberofUnits the most because A) units could be confused with building/dwelling units and B) we are proposing new NumberofUnitsServed elements for shared HVAC/DHW systems, which refers to building/dwelling units.

**Comment by shorowit** [comment]
Slight WG preference for `Count`.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-09-13](https://youtu.be/WB2IYlzBjTM?t=2013)
