### ISSUE TITLE
UnitLocation needs a generic "conditioned space" enumeration

### ISSUE THREAD

**Issue by GamalielL** [hpxmlwg/hpxml#242]
We have "unconditioned space", so it makes sense to have "conditioned space".  The "living space" and "mechanical closet" options are too specific and "other interior" doesn't convey specifically that it's conditioned.  I'm not a fan of growing these lists, so maybe we can establish a convention to handle this.  However, I think "conditioned space" is probably a common designation in software.

**Comment by shorowit** [comment]
General consensus for adding "conditioned space" to the Location and AdjacentTo elements.

**Comment by nmerket** [comment]
🎥 [Discussion in HPXML Working Group Meeting 2022-06-10](https://www.youtube.com/watch?v=bhUQh8x_QmQ&t=1685s)
