### ISSUE TITLE
Rename BaseElements.xsd to HPXMLBaseElements.xsd

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#243]
Would be nice if all three XSD's were prefixed with HPXML, so that A) it's clear that BaseElements.xsd is associated with HPXML, and B) the files end up co-located when in a directory with lots of other files.

**Comment by nmerket** [comment]
[Discussion in 7/21/2021 Working Group Meeting](https://youtu.be/rmpzdDNdAlM?t=50m17s)
