### ISSUE TITLE
Combine/expand exterior finish elements

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#275]
Combine/expand the exterior finish elements for consistency with [the proposed v3.1 InteriorFinish element](https://github.com/hpxmlwg/hpxml/pull/274). This would be a breaking change.

HPXML v3.1 proposed:
- Wall
  - **Siding**
  - **Color**
  - **SolarAbsorptance**
  - **Emittance**
  - InteriorFinish
    - Type
    - Thickness
    - Color

HPXML v4.0 proposed:
- Wall
  - **ExteriorFinish**
    - **Type**
    - **Thickness**
    - **Color**
    - **SolarAbsorptance**
    - **Emittance**
  - InteriorFinish
    - Type
    - Thickness
    - Color

**Comment by shorowit** [comment]
If we did this, we would similarly want to combine roofing options into a single parent element.

We'd also need to decide between, e.g., "ExteriorFinish" and "Siding". The former is consistent with "InteriorFinish" while the latter is more consistent with current HPXML terminology.

**Comment by shorowit** [comment]
WG consensus is that it's not worth the effort.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-09-13](https://youtu.be/WB2IYlzBjTM?t=2592)
