### ISSUE TITLE
NumberofUnits is ambiguous

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#283]
If you have a SFA or MF building, should [NumberofUnits](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/BuildingSummary/BuildingConstruction/NumberofUnits) describe the number of units in the entire building, or the number of units described in the HPXML file? I assumed the former, but I've seen HPXML files with:

```
          <ResidentialFacilityType>2-4 unit building</ResidentialFacilityType>
          <NumberofUnits>1</NumberofUnits>
```

We should document the appropriate approach.

**Comment by shorowit** [comment]
Related issue: https://github.com/hpxmlwg/hpxml/issues/236

**Comment by nmerket** [comment]
- Add `NumberofUnitsinBuilding`
- Update docs on `NumberofUnits` to mean the number of units represented by the `Building` element. It is meant to be used as a multiplier.

**Comment by nmerket** [comment]
🎥  [Discussion in HPXML Working Group Meeting 2022-05-27](https://www.youtube.com/watch?v=7mln2ynMEj4&t=1587s)

**Comment by nmerket** [comment]
🎥 [Discussion in HPXML Working Group Meeting 2022-06-10](https://www.youtube.com/watch?v=bhUQh8x_QmQ&t=1121s)
