### ISSUE TITLE
IDREF attributes called `id` instead of `idref`

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#284]
Some of the elements under Consumption (e.g., [BuildingID](https://hpxml.nrel.gov/datadictionary/3.0.0/Consumption/BuildingID), [CustomerID](https://hpxml.nrel.gov/datadictionary/3.0.0/Consumption/CustomerID), and [UtilityID](https://hpxml.nrel.gov/datadictionary/3.0.0/Consumption/ConsumptionDetails/ConsumptionInfo/UtilityID)) have an `id` attribute (of type IDREF) instead of an `idref` attribute. There are similar elements under Project and probably other places too.

Contrast this with other elements (like [Window/AttachedToWall](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Windows/Window/AttachedToWall) or [Foundation/AttachedToSlab](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Foundations/Foundation/AttachedToSlab)) that correctly have `idref` attributes (of type IDREF).

Shouldn't we replace all `id` attributes (of type IDREF) with `idref` attributes?

This would be a breaking change, so would need to be in v4.0 at the earliest.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-03-14](https://youtu.be/alTvyoUs2qk?t=2439)
