### ISSUE TITLE
Mobile home inputs

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#289]
We should update HPXML to facilitate describing mobile home belly (and wing) foundations.

- New `FoundationType` element?
- New `DuctLocation` choice?
- New `InteriorAdjacentTo`/`ExteriorAdjacentTo` choices for surfaces?
- ???

**Comment by GamalielL** [comment]
New SkirtPresent element - impacts air flow under belly and buffering
InsulationCondition - maybe add additional options to account for variation in belly condition that can be totally ripped open in some cases - OptiMiser has added "perfect" and "critical" options for belly condition.
DuctLocation - maybe multiple options tp account for the wide variation in belly condition.  Some ducts are essentially exposed, while others are behind a good air barrier with insulation.
BellyWrap element - some materials used for the wrap have inherent insulating properties (e.g. fiberboard)
