### ISSUE TITLE
Break out `Inverter` into a standalone component

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#294]
Currently you specify inverter efficiency on a per `PVSystem` basis. For a home with multiple arrays (say, south facing and west facing), that means having to enter the inverter efficiency twice.

It would be better to have a standalone `Inverter` component that can be referenced by the `PVSystem` components. In that way, a home with multiple arrays could have both `PVSystem`s connected to a single `Inverter` or could have each `PVSystem` connected to its own `Inverter`.

Unfortunately this would be a breaking change.

**Comment by shorowit** [comment]
General consensus from the WG that this is an okay change to make.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-09-13](https://youtu.be/WB2IYlzBjTM?t=1653)
