### ISSUE TITLE
Accounts Locked Out

### ISSUE THREAD

**Issue by vargas055** [hpxmlwg/hpxml#305]
While trying to use the API the account appears to be locked. there is no option to reset it. 
Even when we create a brand new account and we try to log in with it right away it says it is locked out for too many wrong attempts even though its a brand new account.

Furthermore trying to log in with random inputs  immediately gives back the same error:

Url: https://hpxml.nrel.gov/api/

In the site:
 Account Locked
There have been more than 3 failed login attempts. You have been locked out from logging into HPXML Toolbox.

In the API
Forbidden (403)

**Comment by nmerket** [comment]
@vargas055 I'll reach out to you separately via email to resolve this.
