### ISSUE TITLE
Add hot water distribution system elements

### ISSUE THREAD

**Issue by nmerket** [hpxmlwg/hpxml#31]
HPXML has water heating systems and water fixtures, but nothing about hot water distribution systems. That data is needed for RESET's Hot Water Calculation Addendum A, which must be included in accredited HERS software and submitted to RESNET for accreditation by August 1, 2015. Here are the data inputs needed for the new hot water algorithms:

* System type
  * Standard systems
      * piping length (ft)
  * Recirculation systems
    * Control type
      * No control or timer control
      * Temperature control
      * Demand control (presence sensor)
      * Demand control (manual)
    * Recirculation piping loop length (ft)
    * Branch piping length (ft)
    * Pump power (W)
* Fixture flow efficiency (probably covered in `WaterFixture`, but should be reviewed)
  * Standard flow
  * Low flow
* Piping insulation
  * None
  * R-3 (or better)
* Drain Water Heat Recovery (DWHR) installed?
  * No
  * Yes
    * Facilities connected (one/all)
    * Equal flow? (yes/no)
    * DWHR Efficiency (%)

**Comment by pfairey** [comment]
Thanks Noel

**Comment by kevinwoley** [comment]
@nmerket - some thoughts here.
Is there a reason to have piping insulation be an enumeration of different R-values? Would it be sufficient to have it be an integer that ranges from 0 to N, where N is a reasonable max?

Is the intent to be able to reference to the WaterFixture(s) elements which are attached to this system?

I assume the DWHR element's presence (or lack of presence) will be how one indicates if there is or is not one installed (i.e. that this isn't proposing a Boolean for that element)?

**Comment by nmerket** [comment]
@kevinwoley 
Or we could just be complete and just have the pipe R-value be a floating point number. I think that would be the way to go.

It's not clear to me yet how `WaterFixture` will relate. It seems most logical to have them be referenced with an id so as not to replicate data points.

Your assumption about DWHR is correct. That's generally the paradigm for other items in the standard.
