### ISSUE TITLE
Allow describing mass floors

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#321]
Spun off from the discussion in https://github.com/hpxmlwg/hpxml/issues/298.

For multifamily buildings, an apartment floor can be a mass floor instead of a frame floor. Some options for handling this in HPXML:
1. Create a new `MassFloor` element, at the same level as the `FrameFloor` element, with inputs specific to mass floors.
2. Rename the `FrameFloor` element to `Floor` and introduce a `FloorType` child element (similar to [`Wall/WallType`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Walls/Wall/WallType)).
3. Use the `Slab` element to describe a mass floor? At a minimum, it would need an `ExteriorAdjacentTo` element.

**Comment by nmerket** [comment]
After much deliberation, we think 2 is the best option.

**Comment by nmerket** [comment]
🎥 [Discussion in HPXML Working Group meeting 2022-06-24](https://www.youtube.com/watch?v=XQyDFqjQoCM&t=1694s)

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-07-12](https://youtu.be/OlWIoAtxmSA)

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-07-12](https://youtu.be/OlWIoAtxmSA?t=706)

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-07-12](https://youtu.be/OlWIoAtxmSA?t=706)

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-10-11](https://youtu.be/YSbsZ_VTfHY?t=1591)
