### ISSUE TITLE
Support Room ACs/PTACs with heating

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#323]
HPXML currently supports room air conditioners as a [`CoolingSystemType`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem/CoolingSystemType). However, there are room ACs on the market that can provide heating -- either via electric resistance or reverse cycle (i.e., a heat pump). See [this example product](https://www.ajmadison.com/cgi-bin/ajmadison/WHT12A33A.html?gclid=Cj0KCQiAw9qOBhC-ARIsAG-rdn76eOtVclkHdAcH5zGExCbFSjA4CcPMrfkzIxreuVdAL09e0iNBUVMaAjpzEALw_wcB).

There are also other products that are slightly different than room air conditioners, such as:
- PTACs/PTHPs (like [this](https://www.amazon.com/COOPER-HUNTER-Packaged-Terminal-Conditioner/dp/B07MBK961H))
- Portable ACs (like [this](https://www.amazon.com/ZAFRO-Portable-Conditioner-Control-Dehumidifier/dp/B09T8ZFXN5))

Our proposed strawman:
- Add "room heat pump" (or "room air conditioner with reverse cycle" or "room air conditioner heat pump"?) as [`HeatPumpType`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/HeatPumpType) enumerations
- Add `IntegratedHeatingSystemFuel`, `IntegratedHeatingSystemCapacity`, `IntegratedHeatingSystemAnnualEfficiency`, and `IntegratedHeatingSystemFractionHeatLoadServed` elements to [`CoolingSystem`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem/CoolingSystem) so that you can describe room ACs or PTACs w/ built-in electric resistance heating. The documentation would need to help explain when to use these `IntegratedHeatingSystem...` elements vs using a separate `HeatingSystem` element. For example, you would not want to use these `IntegratedHeatingSystem...` elements for a central furnace connected with a central air conditioner. 
- Add "packaged terminal air conditioner" as a [`CoolingSystemType`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem/CoolingSystemType) enumeration and add "packaged terminal heat pump" as [`HeatPumpType`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/HeatPumpType) enumerations

**Comment by shorowit** [comment]
Some definitions from ENERGY STAR: https://www.energystar.gov/sites/default/files/ENERGY%20STAR%20Final%20Version%204.2%20Room%20Air%20Conditioners%20Specification_0.pdf

Also, note that there can be other subtle differences -- like a room air conditioner w/ reverse cycle does not have a rated heating efficiency while a PTHP does.

**Comment by RockyMtnBrian** [comment]
I concur with your shift to "integrated" instead of "attached" to describe the heating function in equipment like PTACs & PTHPs.  Interestingly, it appears most PTAC units come with backup electric resistance heating;  you have to special-order units to get them without the backup.

**Comment by shorowit** [comment]
Add "room air conditioner - window", "room air conditioner - portable", "room air conditioner - wall" enumerations for CoolingSystemType. <-- Room AC, Room AC w/ electric resistance

Add "room heat pump - window", "room heat pump - portable", "room heat pump - wall" enumerations for HeatPumpType <- Room AC w/ reverse cycle

Note that Room AC w/ reverse cycle can also have backup strip heat.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-07-12](https://youtu.be/AWL1gD9Dh9M?t=541)

**Comment by yzhou601** [comment]
#240

**Comment by shorowit** [comment]
Remove "with heating" enumerations. Otherwise generally OK with approach.

Consider generalizing RoomCoolingType so it can apply to, e.g., swamp coolers (roof mounted). Also add "other" as a choice.

**Comment by yzhou601** [comment]
> Remove "with heating" enumerations. Otherwise generally OK with approach.
> 
> Consider generalizing RoomCoolingType so it can apply to, e.g., swamp coolers (roof mounted). Also add "other" as a choice.

Is there a better name to suggest for RoomCoolingType?
