### ISSUE TITLE
Add low-e enumerations

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#329]
https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Windows/Window/GlassType only allows "low-e", I propose adding:

- "low-e, solar-control" (or "low-e, low-solar-gain")
- "low-e, insulating" (or "low-e, high-solar-gain")

**Comment by shorowit** [comment]
Home Energy Score, for example, has been using "reflective" for the "low-e, solar-control" (or "low-e, low-solar-gain") situation, but that's not a particularly good mapping. See the warning [here](https://hescore-hpxml.readthedocs.io/en/latest/translation/zone_window.html#double-pane-1) for example.

**Comment by shorowit** [comment]
Document how to map near and far?
Go with "low-e, low-solar-gain" and "low-e, high-solar-gain"

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-07-12](https://youtu.be/OlWIoAtxmSA?t=2721)
