### ISSUE TITLE
Additional CFIS elements

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#330]
There are several control strategies related to central fan integrated supply (CFIS) mechanical ventilation systems that it would be nice to describe in an HPXML file.

Here's a strawman proposal:
- `CFISControls` (to be used when `FanType`="central fan integrated supply")
  - `HasOutdoorAirControl`: boolean (if true, prevents excess ventilation during hours of significant HVAC runtime)
  - `AdditionalRuntimeOperatingMode`: "none", "air handler", or "supplemental fan" (describes if/how the CFIS system provides additional ventilation beyond when the HVAC system is running to meet a given ventilation requirement/target)
  - `SupplementalFan`: idref to another `VentilationFan` (to be used when `AdditionalRuntimeOperatingMode`="supplemental fan")

There is also a control strategy where an exhaust supplemental fan can run simultaneously with the air handler fan (to produce balanced ventilation), but that might be getting too detailed and should be handled by an `extension` element...?

**Comment by RockyMtnBrian** [comment]
Being able to track (and model) these three parameters will provide much better understanding of how these systems are getting installed and how they can be expected to perform.

Reports from field practitioners suggest that these three parameters represent large inconsistencies in the practice of installing systems that are represented as CFIS.  Indeed, the absence of the motorized damper should disqualify a system from being labeled as CFIS, per the definition.  That's also true if AdditionalRuntimeOperatingMode = None.

**Comment by shorowit** [comment]
No objections raised from HPXML WG.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-07-12](https://youtu.be/AWL1gD9Dh9M?t=2480)
