### ISSUE TITLE
Support commercial water heaters

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#333]
In HPXML v3.1, a new [StandbyLoss](https://github.com/hpxmlwg/hpxml/pull/214) element was added for `WaterHeatingSystem`. It has units of F/hr, which is what AHRI collects for [indirect water heaters](https://www.ahridirectory.org/NewSearch?programId=28&searchTypeId=3). However, [commercial water heaters](https://www.ahridirectory.org/NewSearch?programId=27&searchTypeId=3) have units of %/hr and Btu/hr. The best approach would be to add `Units` and `Value` children, though this would be a breaking change.

```
<WaterHeatingSystem>
    ....
    <StandbyLoss>
        <Units>XXXX</Units>
        <Value>XXXX</Value>
    </StandbyLoss>
</WaterHeatingSystem>
```

(Note: The thermal efficiency metric for commercial water heaters [already exists](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/WaterHeating/WaterHeatingSystem/ThermalEfficiency).)

**Comment by shorowit** [comment]
For commercial heat pump water heaters, we should ask for COP. See https://www.energystar.gov/products/commercial_water_heaters/partners for example.

**Comment by RockyMtnBrian** [comment]
The breaking change matches what I assumed would be needed to feed commercial water heater data into OS-ERI.  I'm glad to know that Thermal Efficiency already has an input ready!
**Regarding COP** - That data is not presently available for commercial water heaters in AHRI; in fact, I cannot find commercial HP water heaters in AHRI.  Given this, I think making it a required input is not viable for ERI ratings.

**Comment by shorowit** [comment]
@RockyMtnBrian For what it's worth, ENERGY STAR requires COPs for commercial water heaters, see [here for example products](https://www.energystar.gov/productfinder/product/certified-commercial-water-heaters/results?formId=43739de5-b05d-414e-b723-fe4ecff4a6e5&scrollTo=510&search_text=&fuel_filter=&type_filter=Electric+Heat+Pump&brand_name_isopen=0&markets_filter=United+States&zip_code_filter=&product_types=Select+a+Product+Category&sort_by=brand_name&sort_direction=asc&currentZipCode=27711&page_number=0&lastpage=0). We need to collect some kind of efficiency value for a commercial HPWH, and in the absence of AHRI data, it's the only data I've seen.
