### ISSUE TITLE
Feedback Needed: Supporting measures with multiple installed/replaced components in HPXML

### ISSUE THREAD

**Issue by juliecaracino** [hpxmlwg/hpxml#34]
For example, heat pumps or thermal boundary changes. 

How to handle a single measure that has multiple installed / replaced components that point to different system types including:

1. Making Basement or crawlspace conditioned: Replaced basement ceiling insulation with installed components of rim joist insulation and basement wall insulation
2. Making Attic conditioned (a few variations of this): 
    1. Replaced attic floor insulation with installed components of roof insulation and wall insulation (gable walls)
    1. Replaced attic floor insulation with installed components of roof insulation, wall insulation (gable walls) and knee wall insulation
    1. Replaced knee wall and attic floor insulation with roof insulation

We need to build consensus around this issue in NY.

**Comment by jjaugenbraun** [comment]
For additional context:
The HPXML schema does not limit the number of InstalledComponents or ReplacedComponents on a measure nor does it limit the type of systems referenced. However, to support automated workscope approval for NYSERDA, we implemented a whitelist of measures in NYSERDA's implementation of Optix. 

Currently, the sorts of measures mentioned above (e.g. multiple InstalledComponents on a measure, each with a different system type) are not on the NYSERDA whitelist to prevent ineligible measures from being approved. 

We are looking for input on a path forward that is agreeable to the HPXML modeling tools and works with NYSERDA's program requirements. Options include:
1) Define the specific combination of Installed/ReplacedComponents on a measure that are acceptable and add them to the whitelist (e.g. a measure's InstalledComponents can reference a RimJoist insulation system and a FoundationWall insulation system but if the measure's InstalledComponents reference a Freezer and a RimJoist insulation system, that would not be approved).
2) Stick with the current rules that require a measure to only have one type of system referenced by the InstalledComponent of the measure (although multiple InstalledComponents referencing the same system type are allowed) and submit the overarching measure as multiple measures in HPXML.
3) Some other option?

Thanks,
JJ

**Comment by nmerket** [comment]
It sounds to me like the best option would be to apply @jjaugenbraun's option 1 above. That was the intent of allowing multiple replaced and installed components in a measure in HPXML in the first place. It may be somewhat cumbersome to implement, but honestly those kinds of measures are cumbersome to describe in general terms since there are so many moving parts. Option 2 would be just as cumbersome to implement as well as being a non-standard implementation in my view. Does that answer your question?

**Comment by GamalielL** [comment]
I agree with Noel.  Evaluating these types of measures
component-by-component is really unhelpful.  They can only be considered as
a whole.

**Comment by nmerket** [comment]
@juliecaracino it seems like this has been resolved. Please reopen if not.
