### ISSUE TITLE
New audit button update

### ISSUE THREAD

**Issue by eds-dcameron** [hpxmlwg/hpxml#349]
In Home Auditor the blue button at the top say Create New Load and should say Create New Audit or Run New Audit

**Comment by nmerket** [comment]
@eds-dcameron I think you may have the wrong repo. This is for the HPXML standard itself, not Home Auditor. I encourage you to reach out to them directly with your bug report.

**Comment by eds-dcameron** [comment]
Noel,

My apologies. Please delete me from your group as we no longer support HPXML.

Thanks.

Drew
