### ISSUE TITLE
Clarify HousePressure sign

### ISSUE THREAD

**Issue by brandongallagher** [hpxmlwg/hpxml#37]
I think it would help to clarify and/or restrict the HousePressure field to being either a positive or negative value.  For example, my understanding is that the house is typically held at a lower pressure than the outside, like -50Pa or 50Pa less than outside. However, it seems more convenient to write the HousePressure as just "50" instead of "-50".  I don't care which sign the number has, but it seems like we shouldn't just allow both "50" and "-50" when they really mean the same thing.

We could add a minValue="0" to the HousePressure element, but this probably wouldn't be backward compatible (unless nobody is using negatives).  And/or we could expand the <documentation> to specify whether the number should be positive or negative.

/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement/HousePressure

**Comment by nmerket** [comment]
It seems to me the `TypeOfBlowerDoorTest` would indicate the "sign" of the pressure. I have only ever seen positive numbers in the `HousePressure` field. 

```xml
<AirInfiltrationMeasurement>
    <SystemIdentifier id="airinfilt1"/>
    <TypeOfBlowerDoorTest>pressurization</TypeOfBlowerDoorTest>
    <HousePressure>50</HousePressure>
</AirInfiltrationMeasurement>
```

**Comment by nmerket** [comment]
Technically adding the constraint of `minValue="0"` to this element is breaking backwards compatibility. I'm not sure what to do here. We should ask around and see how it is being used before we break anyone's implementation.

**Comment by brandongallagher** [comment]
I’ve been sending negative 50 (-50).  But I’m happy to change it to positive 50.  I would like you to add the minValue=”0”.

 

-brandon

**Comment by nmerket** [comment]
Let's bring this up on the call.
