### ISSUE TITLE
Add values to Surroundings for stacked multi-family units

### ISSUE THREAD

**Issue by brandongallagher** [hpxmlwg/hpxml#38]
I don't see a good way to indicate that a unit in a multi-family home is stacked above or below the other units in the building.  The //BuildingSummary/Site/Surroundings element has a choices for how many sides the unit is attached on, but doesn't indicate if it is above or below other units.

I wonder if an easy way to indicate the stacked configuration is to add three enumerations to this element for:
stacked below other units
stacked between other units
stacked on top of other units

What do you think?

**Comment by nmerket** [comment]
The only problem I have with this is if it is stacked below/above/between other units *and* attached on the sides. This seems like it should be a separate element to describe its vertical surroundings, maybe call it `VerticalSurroundings`, which is kind of a stupid name. If we did that, the naming of the original element--`Surroundings`--doesn't make a lot of sense either. Anyway, if we could work out the naming issues having two separate elements seems to be the most semantically correct way to do it to me.

**Comment by GamalielL** [comment]
A better design would be to have an AdiabaticSurfaces node with top,
bottom, front, back, left, right boolean elements.  That would be a more
significant change, though.  If we don't want to go that direction, then I
like Noel's suggestion.

**Comment by brandongallagher** [comment]
Either approach works for me.  

 

Another idea would be to add some kind of field to the Foundation and AtticAndRoof elements that indicated they were adjacent to another unit.  The Walls has this with the ExteriorAdjacentTo field.

 

-brandon

**Comment by GamalielL** [comment]
That would be a problem for OptiMiser, because we don't model any details
of adiabatic surfaces. I prefer this to be a general building level
description.
