### ISSUE TITLE
Add "Energy Performance Score" to EnergyScore/ScoreType

### ISSUE THREAD

**Issue by brandongallagher** [hpxmlwg/hpxml#39]
The //BuildingSummary/BuildingConstruction/EnergyScore/ScoreType element has enumerations for different standard energy scores.  Currently there's just HERS and Home Energy Score.  I'd like to add one for "Energy Performance Score".

For convenience, I'd like to just add it as "Energy Performance Score".  

However, the "Energy Performance Score" is being implemented slightly differently in different places.  For example, the Energy Trust of Oregon uses one that presents a slightly adjusted score in MMBTU.  Earth Advantage typically presents our score in kWhe.  Some other programs want to present the score in MMBTU also.  So we could add enumerations of EPS for kWhe and MMBTU if we want, but I'd say we don't need that complexity yet.

**Comment by kmwoley** [comment]
This brings up an interesting issue re: building in Program, Utility, or
Company specific or branded items into HPXML. Energy Performance Score is
something that is specific to a particular company with a brand tied to
that company, and of course with the programs they represent.

My question is if we should we strive to avoid codifying Program, Utility,
or Company specific items directly into HPXML? I'm hopeful that we can find
a way to support the needs of those companies without building into the
standard enumerations which have those branding? If we don't, we as a
community may have a difficult time justifying when or when not to say no
when others make requests to add items which are less innocuous than the
EPS score - "Kevin's Awesome Better Than The Rest Score", for example.

That said, there's an argument to be made that RESNET HERS and the DOE Home
Energy Score already falls into this category of specifically branded
items, so we've already effectively said this is a fine and supported thing
to do.

If the working group generally isn't concerned about this, this'll be the
last word I say on the topic. I'm not sure how concerned I am with it
myself, frankly, and may not be worth the time/energy to find an
alternative in this case but thought it worthy of at least some
consideration.

Thanks,
Kevin

**Comment by brandongallagher** [comment]
Kevin, that’s a good point.  I agree with you about the dangers of supporting the specific branding in HPXML.  I think it would probably be better to not have any enumerated ScoreTypes.  But if we are going to keep HERS and HES, then we should support more.  Maybe we could make the ScoreType just a string rather than an enumerated list, and leave it up to each score provider to make it clear how their particular score should be expressed in HPXML.  That way there could be consistency in the score name, but it wouldn’t be on HPXML to regulate it.

 

FYI… I plan to rebrand all our marketing materials with “Kevin's Awesome Better Than The Rest Score”.  It has a nice ring to it.

 

-brandon

**Comment by GamalielL** [comment]
Changing the nature of the existing element to a string will require
everyone who is already generating of interpreting this element to rewrite
code.  I agree it's preferable to add flexibility rather than new
enumerations.  Maybe we could add an Other to the current enumerations and
then a new OtherName string element.  That would add the flexibility
without breaking backwards compatibility.

On Mon, Nov 2, 2015 at 10:52 AM, Brandon Gallagher <notifications@github.com

**Comment by juliecaracino** [comment]
I would suggest a middle ground here. Supporting a nationally branded score like HES is OK. But having to support state or regional specific scores may be more problematic from a maintenance point of view. It may be that the WG--5 votes on the inclusion of a branded score based on a set of criteria we develop. For state or regional specific scores we should create generic elements to accommodate these for now.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Mon, Nov 2, 2015 at 8:15 AM -0800, "GamalielL" <notifications@github.com<mailto:notifications@github.com>> wrote:

Changing the nature of the existing element to a string will require
everyone who is already generating of interpreting this element to rewrite
code. I agree it's preferable to add flexibility rather than new
enumerations. Maybe we could add an Other to the current enumerations and
then a new OtherName string element. That would add the flexibility
without breaking backwards compatibility.

On Mon, Nov 2, 2015 at 10:52 AM, Brandon Gallagher <notifications@github.com
> wrote:

> Kevin, that's a good point. I agree with you about the dangers of
> supporting the specific branding in HPXML. I think it would probably be
> better to not have any enumerated ScoreTypes. But if we are going to keep
> HERS and HES, then we should support more. Maybe we could make the
> ScoreType just a string rather than an enumerated list, and leave it up to
> each score provider to make it clear how their particular score should be
> expressed in HPXML. That way there could be consistency in the score name,
> but it wouldn't be on HPXML to regulate it.
>
>
>
> FYI... I plan to rebrand all our marketing materials with "Kevin's Awesome
> Better Than The Rest Score". It has a nice ring to it.
>
>
>
> -brandon
>
>
>
> From: Kevin Woley [mailto:notifications@github.com]
> Sent: Friday, October 30, 2015 5:10 PM
> To: hpxmlwg/hpxml <hpxml@noreply.github.com>
> Cc: Brandon Gallagher <bgallagher@cakesystems.com>
> Subject: Re: [hpxml] Add "Energy Performance Score" to
> EnergyScore/ScoreType (#39)
>
>
>
> This brings up an interesting issue re: building in Program, Utility, or
> Company specific or branded items into HPXML. Energy Performance Score is
> something that is specific to a particular company with a brand tied to
> that company, and of course with the programs they represent.
>
> My question is if we should we strive to avoid codifying Program, Utility,
> or Company specific items directly into HPXML? I'm hopeful that we can find
> a way to support the needs of those companies without building into the
> standard enumerations which have those branding? If we don't, we as a
> community may have a difficult time justifying when or when not to say no
> when others make requests to add items which are less innocuous than the
> EPS score - "Kevin's Awesome Better Than The Rest Score", for example.
>
> That said, there's an argument to be made that RESNET HERS and the DOE Home
> Energy Score already falls into this category of specifically branded
> items, so we've already effectively said this is a fine and supported thing
> to do.
>
> If the working group generally isn't concerned about this, this'll be the
> last word I say on the topic. I'm not sure how concerned I am with it
> myself, frankly, and may not be worth the time/energy to find an
> alternative in this case but thought it worthy of at least some
> consideration.
>
> Thanks,
> Kevin
>
>
>
> On Fri, Oct 30, 2015 at 7:55 AM Brandon Gallagher <
> notifications@github.com <mailto:notifications@github.com> >
> wrote:
>
> > The //BuildingSummary/BuildingConstruction/EnergyScore/ScoreType element
> > has enumerations for different standard energy scores. Currently there's
> > just HERS and Home Energy Score. I'd like to add one for "Energy
> > Performance Score".
> >
> > For convenience, I'd like to just add it as "Energy Performance Score".
> >
> > However, the "Energy Performance Score" is being implemented slightly
> > differently in different places. For example, the Energy Trust of Oregon
> > uses one that presents a slightly adjusted score in MMBTU. Earth
> Advantage
> > typically presents our score in kWhe. Some other programs want to present
> > the score in MMBTU also. So we could add enumerations of EPS for kWhe and
> > MMBTU if we want, but I'd say we don't need that complexity yet.
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hpxmlwg/hpxml/issues/39>.
> >
>
>
>
> -
> Reply to this email directly or view it on GitHub <
> https://github.com/hpxmlwg/hpxml/issues/39#issuecomment-152677007> . <
> https://github.com/notifications/beacon/AJB5xwjeGR9aYt1qzvEFSnNbWLSQ39u1ks5pA_5FgaJpZM4GZDAa.gif>
>
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/hpxmlwg/hpxml/issues/39#issuecomment-153059863>.
>

-

**Comment by kevinwoley** [comment]
@GamalielL 's suggestion might be a nice way to achieve that middle ground that @juliecaracino is talking about. Score types that get approved by WG-5 become enumerations listed in the standard. Those that don't, can use the "Other" enumeration and identify themselves in an (Optional) text field. 

Thank you all for the discussion here!
Kevin

**Comment by nmerket** [comment]
This seems like a reasonable compromise. For the record, we already have an "other" enumeration for score type. It would just be a matter of adding the additional text description field. I also think we should have a date field to go with the score. I can't remember if I added that as another issue or not.

**Comment by brandongallagher** [comment]
I definitely agree with the date.

 

-brandon
