### ISSUE TITLE
Electric panels

### ISSUE THREAD

**Issue by shorowit** [hpxmlwg/hpxml#396]
Important when discussing new equipment that potentially requires higher voltage service.

Some initial thoughts from @nmerket:

- Manufacturer
- Model
- Max current rating
- Some way to indicate sub panels
- Whether/how much space is there for new breakers in the panel

Some additional thoughts from Kelly at Radiant Labs:

- Location
- Type (main/sub panel)
- Count of total breakers
- Count of breakers used 
- ID (plus idrefs to relate other systems to the panel -  not sure if you'd want to get this complicated)
- Voltage (some panels in older homes can only support 120V)

**Comment by nmerket** [comment]
Electric panel max amps is required for the HOMES rebates and is in the data and tools guide for a required input to be sent in HPXML.
