### ISSUE TITLE
Add date to home scores (HEScore/HERS/etc)

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#40]
Add a "year" for when the Energy Scores (Home Energy Score, HERS) were completed

**Comment by brandongallagher** [comment]
Can this be the score date?  If so, I'd go for the full date, not just the
year.  We could add ScoreDate to the EnergyScore element.

-brandon

**Comment by nmerket** [comment]
I'd prefer the full date as well. Changing it.
