### ISSUE TITLE
Add Sauna

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#41]
Add sauna data field

**Comment by nmerket** [comment]
@RebHudson what information about saunas?

**Comment by RebHudson** [comment]
Whether the home has a sauna

**Comment by nmerket** [comment]
This could just be an additional plug load in `MiscLoads/PlugLoad` unless we have some additional information we want to capture. That does allow us to specify if the load exists in a space and that the internal gains from that load are to go into that space.
