### ISSUE TITLE
Add electric well pump

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#42]
Add electric well pump data field

**Comment by nmerket** [comment]
@RebHudson What information do we want to collect about electric well pumps?

**Comment by RebHudson** [comment]
if the home has an electric well pump

**Comment by nmerket** [comment]
Should we have more performance information? Can someone throw a straw man out of what this should contain?

**Comment by GamalielL** [comment]
I thought that we were just going to add an enumeration under PlugLoadType

**Comment by nmerket** [comment]
That's fine with me too.
