### ISSUE TITLE
Add additional certifications to the third party enumerations: 

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#43]
Add the following enumerations: ENERGY STAR Certified Home, Indoor airPLUS, WaterSense, DOE Zero Energy Ready Home, NGBS Green Certification (different levels), Enterprise Green Communities, Earthcraft, Environments for Living,

**Comment by nmerket** [comment]
We have several different `ThirdPartyCertification` enumeration lists depending on what is being certified. Which one(s) are you referring to here?

**Comment by RebHudson** [comment]
I meant this for the whole house certifications.

**Comment by tglidden** [comment]
Build It Green would like to add "Green Point Rated" to the enumeration for the whole house certifications iteration of the 'ThirdPartyCertification' list.

**Comment by Tedkidd** [comment]
Will it also have space for the rating, the rater, the provider, and the builder?

**Comment by eocathcart** [comment]
Other certifications needed, PHIUS+, Earth Advantage (various levels), BuiltGreen, and Minnesota Greenstar
