### ISSUE TITLE
Have ducts sealed associated with a specific year completed

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#45]
Add the association with the year with the job task

**Comment by nmerket** [comment]
This and #48 have the same dilemma for me. This could be inferred from the project date that contains the measure that references this component in the post-retrofit. The problem arises in the audit `Building` node where this action may have been performed in the past. Those dates could be pretty unreliable, though. 

> Energy Auditor: "I see you have mastic on your ducts. Do you know when this air sealing was done?", 
> Homeowner: (confused, checks his fly) "Let's see, I think that was the same year we remodeled the bathroom. Or did we have that done after the basement flooded? So it was either 1998 or 2013. Yeah."

I'd be interested to hear others' take on this, though.
