### ISSUE TITLE
Add LEED Bronze

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#46]
There currently is not a LEED Bronze option. Is it assumed that if LEED Certified is selected that the job was a LEED Bronze? Or should LEED Bronze be specifically added to the list?

**Comment by nmerket** [comment]
Visiting the [Guide to LEED Certification for Homes](http://www.usgbc.org/cert-guide/homes#certify) they do not list a Bronze level. They have Certified, Silver, Gold, Platinum. I assume that people are informally calling the "Certified" level "Bronze". I recommend leaving the enumerations as is to match the levels USGBC has set.
