### ISSUE TITLE
Add Geothermal desuperheater

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#51]
Add this water heater type

**Comment by nmerket** [comment]
@RebHudson Do we need any additional information besides the enumeration?

**Comment by RebHudson** [comment]
The desuperheater is usually connected to a standard electric water heater. I think just the enumeration is needed since the other characteristics for an electric water heater already exist. I’d defer to others who may know better how this would fit.

Rebecca Hudson
ENERGY STAR Residential Branch
202-343-9862
hudson.rebecca@epa.gov
