### ISSUE TITLE
Add wind 

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#52]
Add wind power into the schema in a similar way as PV

**Comment by nmerket** [comment]
I am not familiar with the properties of small, residential wind systems. Do we have any volunteers to flesh this out?

**Comment by RebHudson** [comment]
Some data points: 
year installed
rated capacity
certification (small wind certification is one but I dont know if there are more. http://smallwindcertification.org/certified-small-turbines/) 
annual output (actual) with year achieved

On the small wind certification page there are additional characteristics. I am not sure if they are useful: 
Turbine (e.g., Excel 10, Kestrel e400nb)
"Certification Type" designates to which Standard(s) the applicant is pursuing SWCC certification: AWEA 9.1-2009 (AWEA).

"AWEA Rated Annual Energy" is the calculated total energy that would be produced during a one-year period with an average wind speed of 5 m/s (11.2 mph)

"AWEA Rated Sound Level" is the sound pressure level (dBA) not exceeded by the wind turbine 95% of the time at a distance of 60 meters from the rotor with an average wind speed of 5 m/s (11.2 mph).

"AWEA Rated Power" is the wind turbine’s power output at 11 m/s (24.6 mph). Manufacturers may still describe or name their wind turbine models using a nominal power (e.g. 5 kW S-343).

"Peak Power" is the highest point on the certified power curve

**Comment by RebHudson** [comment]
More information on certification is available here: http://www.energy.gov/energysaver/articles/want-tax-credit-small-wind-system-be-sure-its-certified

There seem to be two options: small wind certification council (SWCC) and Intertek although there could be ones added. List of certified turbines: http://www.irecusa.org/credentialing/certified-small-wind-turbines/
