### ISSUE TITLE
Add new characteristics for PV (and wind if added)

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#53]
Add "Year Installed, "Annual Output", "Levelized Cost of Electricity"

**Comment by nmerket** [comment]
We would need clear definitions of how Annual Output and Levelized Cost of Electricity are to be calculated.

**Comment by nmerket** [comment]
Need to add to wind

**Comment by RebHudson** [comment]
The new wind tree has year installed and its version of annual output so I think the only addition needed is levelized cost of electricity
