### ISSUE TITLE
PV financing

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#54]
Add whether the panels are leased, self-financed, PPA or other.

**Comment by nmerket** [comment]
There is an element `Building/BuildingDetails/Systems/Photovoltaics/PVSystem/Ownership` that has the possible enumerations of "leased" or "owned". This could be expanded with additional appropriate enumerations. I'm thinking the appropriate list should be:

 - leased
 - owned
 - power purchase agreement
 - other

Any others?

**Comment by Gavinhastings** [comment]
We are starting to see utility owned systems were utilities are in effect renting the home owners roof space, but they receive no benefit from the solar production.



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by nmerket** [comment]
If you were to describe that in a word or three that could be used as the enumeration would it be "utility owned"? Something else?
