### ISSUE TITLE
Renewable ready characteristics

### ISSUE THREAD

**Issue by RebHudson** [hpxmlwg/hpxml#55]
Add the following renewable ready characteristics: 
Pre-wired to install system
Evaluated for solar availability
Electrical panel can handle a system

**Comment by nmerket** [comment]
Seems only relevant to PV systems. 
Related to #54 and #53.

**Comment by nmerket** [comment]
from @RebHudson:
> This is for homes that do not yet have a solar system installed. I don’t know if that needs to be clarified.  I would think that other than solar availability, they would apply to a wind system too.

**Comment by RebHudson** [comment]
The PV ready checklist is here: 
https://www.energystar.gov/ia/partners/bldrs_lenders_raters/rerh/docs/RERH_Guidance_PV_Checklist.pdf?d219-aaee 
The guide is here: https://www.energystar.gov/ia/partners/bldrs_lenders_raters/rerh/docs/Renewable_Energy_PV.pdf?a9d2-69d7

Any/all of these could be items under "renewable ready". Sections 1 and 3 are most relevant for my use case
