### ISSUE TITLE
Use BPI 2200 data ids in HPXML schema annotations

### ISSUE THREAD

**Issue by nmerket** [hpxmlwg/hpxml#57]
In the [BPI-2200 standard](http://www.bpi.org/Web%20Download/BPI%20Standards/BPI-2200-S-2013%20Standard%20for%20Home%20Performance-Related%20Data%20Collection%202013-06-18.pdf), there are numbers to identify each data element. These numbers should be included in the HPXML annotations for reference. Conversely, it would be useful in the next update to 2200 to include an XPath expression in 2200 to denote where each of those elements exist in HPXML.

**Comment by DebraLittle** [comment]
Agreed

**Comment by nmerket** [comment]
This will be a pretty big lift.

**Comment by juliecaracino** [comment]
We're exploring online tools that can help align the standards so we don't have to manually update numbers in 2200.
