### ISSUE TITLE
Modeling ECM Motors in HPXML

### ISSUE THREAD

**Issue by juliecaracino** [hpxmlwg/hpxml#75]
NYSERDA would like to collect kWh savings from ECMs that are installed as part of a furnace (through HPXML). There does not seem to be a standard way of collecting this information through HPXML so we are getting this information differently from tools. Some tools roll savings into the heating measure and some pass the information through other measures.

How can we standardize our approach so that the program can distinguish between multiple improvements on the same distribution system without having to add a measure code.

@jjaugenbraun @kmwoley can explain this in more detail.

Comments would be appreciated.

**Comment by kmwoley** [comment]
My understanding is that there is no way to structure this without
introducing a separate Measure/Measure code to capture the kWh savings
specifically from the ECMs. Each Measure collects the savings of all of the
aspects of that particular measure, and there's not a way to subdivide
those savings within an individual Measure.

**Comment by GamalielL** [comment]
If the only change to the furnace was the ECM retrofit, then the measure
referencing the furnace should only have kW savings.  Isn't that enough to
identify an ECM measure?  What other measure types are people using?

**Comment by juliecaracino** [comment]
PSD has historically passed this information to us as an "appliance." I believe their concern is how NYSERDA would parse ECM savings if multiple distribution improvements are made for a single system.

@andrulis can explain more

**Comment by GamalielL** [comment]
You are already handling multiple distribution improvements (duct sealing
and duct insulation) via measure codes.

If the ECM is being retrofit to the furnace's integrated blower motor,
shouldn't it be considered an improvement to the Furnace.

**Comment by nmerket** [comment]
Okay, so do I need to add or change something in the standard or are we good?
