### ISSUE TITLE
Project IDs redo

### ISSUE THREAD

**Issue by nmerket** [hpxmlwg/hpxml#85]
A `Project` node has three possible places to have IDs:
- `Project/BuildingID` - _required_. Why is there only one? Usually projects have two building associated with them.
- `Project/ProjectID` - _optional_. Why is this optional?
- `Project/ProjectDetails/ProjectSystemIdentifiers` - _0 to many_. I'm not really sure what these are for and I've seen different vendors use them differently, so I'm not alone here. Is this to reference the buildings or projects somehow?

These seem to be ambiguous and not really meet the needs of a project. I propose changing this so that projects have a:
- `Project/ProjectID` - _required_, this is an id for the project itself.
- `Project/PreBuildingID` - _required_, this is an id for the pre-retrofit building.
- `Project/PostBuildingID` - _required_, this is an id for the post-retrofit (proposed or actual) building.

Furthermore, we could probably do away with the `Project/ProjectDetails/ProjectStatus` element since it is redundant with the one in the `Building` node.

**Comment by eocathcart** [comment]
If a project is part of a program that is including Home Energy Score the building_ID is used as an identifier of that home's address and is passed through to other software platforms. Address verification is very challenging and attaching a Building_ID signifier is useful as a second form of verification under these scenarios.
