### ISSUE TITLE
Combine XSD's into a single file

### ISSUE THREAD

**Issue by jefffriesen** [hpxmlwg/hpxml#86]
Does anyone object to distributing the HPXML schema as a single xsd instead of the three that we have now? Some platforms and tooling don't do well when having to validate against multiple schemas with `includes`. 

Would that make it harder for anyone out there?

If people agree with this, we could initially distribute a single xsd in addition to the three xsd's which wouldn't be a breaking change. Eventually we could distribute only the single xsd during one of the major breaking changes.

**Comment by nmerket** [comment]
@jefffriesen I take issue to having duplicate xsds because that means that for any change I make, I have to do it in two places. However, thinking more about it, I don't think this change would be a breaking change in that it wouldn't change what an HPXML file would look like or how it would be formatted, it would just simplify the distribution of the schema. Nevertheless, I don't know for sure if it would cause problems for others depending on the tools they're using to handle the xml, so I'll leave that for them to discuss here.

**Comment by brandongallagher** [comment]
I think it would be great to combine them.

-brandon

**Comment by GamalielL** [comment]
The feedback from our team is that it would require significant redevelopment work to move from the current three file structure to a single file.  We would not support a change the eliminate the three files structure as an option. Is it not possible to develop an automated solution that generates an optional single file using the existing three files as an inputs, which could be utilized at release time? Note that many APIs, for example Portfolio Manager, require multiple files.

**Comment by kevinwoley** [comment]
I would like to understand the potential benefits of making this change.

From our perspective, this is represents work with no clear benefit and thus I don't support making this change. However, there may be benefit for others, so I'd like to understand that before we vote.

**Comment by nmerket** [comment]
Let's discuss on the call tomorrow.

**Comment by jefffriesen** [comment]
Unfortunately I can't make today's call to discuss this. Nothing's changed on my end - I would still be very helpful for us to combine these into a single xsd.  XML is rarely used on the platform we use and there only basic or buggy tools for generating and validating XML. However, if this causes too many problems for others in this group we will try to figure out a different solution. 

Thanks for considering it.

**Comment by nmerket** [comment]
Here's what I can do: I will create a script that generates a single-file xsd from the three xsds we have now. We'll continue to do all our work on the three files as we do now, but generate a single-file xsd included in the release for those who want to use it.

**Comment by jefffriesen** [comment]
That sounds great and solves everyone's problem (except you having to do the extra work...). Thanks

**Comment by GamalielL** [comment]
Thanks, Noel!
