### ISSUE TITLE
MaxAmbientCOinLivingSpaceDuringAudit is misplaced in the HPXML schema

### ISSUE THREAD

**Issue by adamsten** [hpxmlwg/hpxml#87]
MaxAmbientCOinLivingSpaceDuringAudit is misplaced in the HPXML schema. According to BPI 2200, the test is only performed once, not on a per appliance basis:

![screen shot 2016-05-31 at 1 12 42 pm](https://cloud.githubusercontent.com/assets/1406536/15789398/354bde24-2989-11e6-8cb5-040ce5abc040.png)

However, in the schema, it is buried inside the Combustion Appliance Tests that happen on a per appliance basis:

HealthAndSafety / CombustionAppliances / CombustionApplianceZone / CombustionApplianceTest / CarbonMonoxideTest / MaxAmbientCOinLivingSpaceDuringAudit

![screen shot 2016-06-01 at 10 59 45 am](https://cloud.githubusercontent.com/assets/1406536/15789417/5e7622f0-2989-11e6-9127-49cb069405de.png)

(that’s from Noel's audit.xml example)

In my mind, it would make more sense to go here:

HealthAndSafety / CombustionAppliances / MaxAmbientCOinLivingSpaceDuringAudit

Currently, I know folks are just collecting it once and putting it in everywhere in the HPXML. This would likely be a breaking change.

**Comment by nmerket** [comment]
I know so little about the CAZ testing. Could someone else look at this and verify that this needs to be changed?

**Comment by GamalielL** [comment]
I'm not a CAZ expert either, but I consulted several of our expert users
and came to the same conclusion, back when I was implementing this element
for OptiMiser.

**Comment by juliecaracino** [comment]
Agree that it should be changed. The BPI-2200 will also now be consistent with the revised BPI-1200.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-03-14](https://youtu.be/alTvyoUs2qk?t=2602)
