### ISSUE TITLE
Repository for MeasureCodes

### ISSUE THREAD

**Issue by andybardwell** [hpxmlwg/hpxml#9]
Measures can be specified by MeasureCode or by ReplaceComponents and InstalledComponents. 
MeasureCodes add information in the case when components are also specified.
NY and CA are considering using MeasureCodes to specify some measures.  A Repository for MeasureCodes is needed to coordinate and communicate MeasureCode specifications, and to avoid proliferation of functionally duplicate codes. This repository might include:

+ Program initiator
+ MeasureCode
+ Description and purpose
+ Allowed InstalledComponents that would be consistent with the MeasureCode
+ Restrictions on elements specifying the InstalledComponents
+ Allowed ReplacedComponents that would be consistent with the MeasureCode
+ Restrictions on elements specifying the ReplacedComponents
+ Restrictions on other HPXML elements to be consistent with this MeasureCode

**Comment by nmerket** [comment]
This is really old. It sounds like most have agreed to have the programs document their own measure codes when they are needed. I'm going to close this. If anyone still thinks this needs addressing, please reopen the ticket.
