### ISSUE TITLE
Proposed change to documentation on BPI2400Inputs/CalibrationQualification

### ISSUE THREAD

**Issue by GamalielL** [hpxmlwg/hpxml#99]
Bruce Harley suggested to me that the documentation for this element lacked clarity leading to the possibility that it could be interpreted to apply to the model calibration rather than the bill sufficiency.  Together we propose the following edit:

“This identifies which data quality requirements _(if any)_ were met by the bills for ~~each~~ _the relevant_ energy source, and therefore which calibration ~~measure~~ _metrics (if any)_ are used to determine _whether the calibrated_ model _is accepted_~~acceptance~~."

**Comment by nmerket** [comment]
I'll add it to 2.3
